// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    CarbonBlog: typeof import('~icons/carbon/blog')['default']
    CarbonBorderFull: typeof import('~icons/carbon/border-full')['default']
    CarbonEmail: typeof import('~icons/carbon/email')['default']
    CarbonFolderDetails: typeof import('~icons/carbon/folder-details')['default']
    CarbonLogoGithub: typeof import('~icons/carbon/logo-github')['default']
    CarbonLogoLinkedin: typeof import('~icons/carbon/logo-linkedin')['default']
    CarbonLogoTwitter: typeof import('~icons/carbon/logo-twitter')['default']
    CarbonMoon: typeof import('~icons/carbon/moon')['default']
    CarbonSun: typeof import('~icons/carbon/sun')['default']
    CardProject: typeof import('./components/home/CardProject.vue')['default']
    CardSkill: typeof import('./components/home/CardSkill.vue')['default']
    CardTimeline: typeof import('./components/home/CardTimeline.vue')['default']
    Header: typeof import('./components/Header.vue')['default']
    ListInfo: typeof import('./components/ListInfo.vue')['default']
    ListPosts: typeof import('./components/blog/ListPosts.vue')['default']
    ListProjects: typeof import('./components/projects/ListProjects.vue')['default']
    SectionExperience: typeof import('./components/home/SectionExperience.vue')['default']
    SectionJumbotron: typeof import('./components/home/SectionJumbotron.vue')['default']
    SectionProjects: typeof import('./components/home/SectionProjects.vue')['default']
    SectionSkill: typeof import('./components/home/SectionSkill.vue')['default']
  }
}

export { }
